name: ibank
description: "Manage your finances with ease and security."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  device_preview_screenshot: ^1.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
